import Mathlib.LinearAlgebra.LinearIndependent.Defs
import QEC.Stabilizer.BinarySymplectic.Core
import QEC.Stabilizer.BinarySymplectic.SymplecticInner
import QEC.Stabilizer.BinarySymplectic.CheckMatrix
import QEC.Stabilizer.Core.SubgroupLemmas
import QEC.Stabilizer.PauliGroup.NQubitElement

namespace Quantum

variable {n : ℕ}

/-!
# Equivalence: independent generators ↔ rows linearly independent

For a list `L` of n-qubit Pauli group elements, we relate:
- **Subgroup.IndependentGenerators (listToSet L)**: no element of `L` lies in the subgroup
  generated by the others.
- **NQubitPauliGroupElement.rowsLinearIndependent L**: the rows of the check matrix (symplectic
  vectors) are linearly independent over ZMod 2.

Row independence is equivalent to: the list has no duplicates and the set of elements
is an independent generating set (no element in the closure of the others).

**Phase-zero restriction:** The equivalence requires that every element of `L` has phase 0
(i.e. `phasePower = 0`). Without this, the theorem is false: e.g. `[X, iX]` (same operator,
different phase) has linearly dependent check-matrix rows but the set `{X, iX}` is
group-theoretically independent (neither lies in the closure of the other).
-/

namespace NQubitPauliGroupElement

/-- The set of elements appearing in the list `L`. -/
def listToSet (L : List (NQubitPauliGroupElement n)) : Set (NQubitPauliGroupElement n) :=
  setOf (· ∈ L)

/-- Every element of the list has phase 0 (no global phase factor i, -1, or -i). -/
def AllPhaseZero (L : List (NQubitPauliGroupElement n)) : Prop :=
  ∀ g ∈ L, g.phasePower = 0

/-- Row independence of the check matrix is equivalent to no duplicates and set independence,
  **for phase-zero lists only.** Without `AllPhaseZero L`, the theorem is false (e.g. `[X, iX]`).

  **Proof sketch (to be completed):**
  - **→** From row independence deduce no duplicate rows (hence `L.Nodup`) and set independence.
  - **←** From `L.Nodup` and set independence, deduce row independence (e.g. by contrapositive
    using `linearIndependent_iff_ker` and the product-of-generators/symplectic-sum argument). -/
theorem independentGenerators_iff_rowsLinearIndependent (L : List (NQubitPauliGroupElement n))
    (hPhase : AllPhaseZero L) :
    rowsLinearIndependent L ↔ L.Nodup ∧ Subgroup.IndependentGenerators (listToSet L) := by
  sorry

end NQubitPauliGroupElement

end Quantum
